---
matrix: &default
  distro:
    - almalinux/8/cloud
    - amazonlinux
    - centos/7/cloud
    - debian/11/cloud
    - fedora/35/cloud
    - oracle/8/cloud
    - rockylinux/8/cloud
    - ubuntu/20.04/cloud

adguardhome:
  matrix:
    <<: *default
    install_method: [binary]
    include:
      - distro: rockylinux/8/cloud
        install_method: docker
      - distro: ubuntu/20.04/cloud
        install_method: snap

epel:
  matrix:
    <<: *default
    exclude:
      - distro: debian/11/cloud
      - distro: ubuntu/20.04/cloud

lxd:
  matrix:
    <<: *default
    exclude:
      - distro: debian/11/cloud
      - distro: fedora/35/cloud

traefik:
  matrix:
    <<: *default
    install_method: [binary]
    include:
      - distro: rockylinux/8/cloud
        install_method: docker
