---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    adguardhome_install_method: "{{ lookup('env', 'INSTALL_METHOD') | default('binary', true) }}"

  pre_tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Install snapd
      ansible.builtin.include_role:
        name: bonddim.linux.snapd
      when:
        - adguardhome_install_method == 'snap'
        - 'not "snapd.service" in ansible_facts.services'

    - when: adguardhome_install_method == 'docker'
      block:
        - name: Install Docker daemon
          ansible.builtin.include_role:
            name: bonddim.linux.docker
          when: 'not "docker.service" in ansible_facts.services'

        - name: Install pip package
          ansible.builtin.package:
            name: python3-pip
            state: present

        - name: Install Docker SDK for Python
          ansible.builtin.pip:
            name:
              - docker
              - six
            state: present

  roles:
    - bonddim.linux.adguardhome
